main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name='index'),
]

pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('api/', include('menu.api_urls')),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

menu/models.py
from django.db import models


# Create your models here.
class Pizza(models.Model):
    name = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    price = models.FloatField(default=0)
    vegetarian = models.BooleanField(default=False)

    def __str__(self):
        return self.name

main/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'main/index.html')

menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from .models import Pizza


# Create your views here.
def index(request):
    pizzas = Pizza.objects.all().order_by('price')
    return render(request, 'menu/index.html', {'pizzas': pizzas})


def api_get_pizzas(request):
    pizzas = Pizza.objects.all().order_by('price')
    json = serializers.serialize('json', pizzas)
    return HttpResponse(json)

main/templates/main/index.html
{% load static %}
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Pizza Mama</title>
		<link rel="stylesheet" href="{% static 'main/style.css' %}">
	</head>
	<body>
		<div class='centered'>
			<img id='small_logo' src="{% static 'main/images/main_logo.png' %}">
			<a href="{% url 'menu:index' %}">Go to the menu</a>
		</div>
	</body>
</html>

menu/templates/menu/index.html
{% load static %}
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Pizza menu</title>
		<link rel="stylesheet" href="{% static 'menu/style.css' %}">
	</head>
	<body>
		<a href="{% url 'main:index' %}">
			<img id='small_logo' src="{% static 'menu/images/small_logo.png' %}">
		</a>
		<div class='menu_title'>
			<h1>Pizzas</h1>
		</div>
		<div class='menu_list'>
			{% for pizza in pizzas %}
			<div class='menu_list_item'>
				<span class='menu_list_title'>{{pizza.name}}</span>
				<span class='menu_list_price'>{{pizza.price | floatformat:2}}€</span>
				<span class='menu_list_ingredients'>{{pizza.ingredients}}</span>
				{% if pizza.vegetarian %}
				<span class='menu_list_badge'>VEGETARIAN</span>
				{% endif %}
			</div>
			{% endfor %}
		</div>
	</body>
</html>